set sql dialect 3;

/********************************************************************/
/* table CATALOGUE                                                  */
/********************************************************************/

create table t_catalogue(
    t_catalogue_id d_id_char not null,
    t_fournisseur_id d_id_char not null,
    libelle varchar(100) not null,
    fin_validite date,
    constraint pk_catalogue primary key (t_catalogue_id),
    constraint fk_cat_fournisseur foreign key (t_fournisseur_id) references t_fournisseur(t_fournisseur_id) on delete cascade);

create unique index unq_catalogue on t_catalogue(t_fournisseur_id, libelle);

/********************************************************************/
/* table CATALOGUE_LIGNE                                            */
/********************************************************************/

create table t_catalogue_ligne(
    t_catalogue_ligne_id d_id_int generated by default as identity not null,
    t_catalogue_id d_id_char not null,
    t_produit_id d_id_char not null,
    prix_achat numeric(10, 3) not null,
    remise numeric(10, 3) default 0 not null,
    maj_tarif date default current_date not null,
    constraint pk_catalogue_ligne primary key(t_catalogue_ligne_id),
    constraint fk_catlg_catalogue foreign key(t_catalogue_id) references t_catalogue(t_catalogue_id) on delete cascade,
    constraint fk_catprd_produit foreign key(t_produit_id) references t_produit(t_produit_id) on delete cascade);
