set sql dialect 3;

/********************************************************************/
/* table ADRESSE                                                    */
/********************************************************************/

create table t_adresse(      
    t_adresse_id d_id_int generated by default as identity not null,
    rue_1 varchar(50),
    rue_2 varchar(50),
    code_postal varchar(10),
    ville varchar(100),
    pays varchar(100),
    telephone varchar(30),
    portable varchar(30),
    fax varchar(30),
    email varchar(200),
    constraint pk_adresse primary key(t_adresse_id)
);

/********************************************************************/
/* table CONTACT                                                    */
/********************************************************************/

create table t_contact(
    t_contact_id d_id_int generated by default as identity not null,
    nom varchar(50) not null
        constraint chk_cont_nom check (char_length(nom) > 0),
    prenom varchar(50) not null,
    t_adresse_id d_id_int,
    commentaire blob sub_type 1,
    constraint pk_contact primary key(t_contact_id),
    constraint fk_cont_adresse foreign key(t_adresse_id) references t_adresse(t_adresse_id) on delete cascade);